import pygame

class Scene:
    def __init__(self):
        self.surface_display = pygame.display.get_surface()
        self.width, self.height = self.surface_display.get_size()
        self.half_width, self.half_height = self.width // 2, self.height // 2
        
    def on_enter(self): ...
    def on_update(self): ...
    def on_draw(self): ...
    def on_input(self, event: pygame.event.EventType): ...
    def on_exit(self): ...